image: playpen-runner

variables:
  DOCKER_DRIVER: overlay2
  PLAYPEN_NAME: clash
  PACKAGE_PATH: plugins/
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache decompiled minecraft-server and Spigot-API artifacts
cache:
  paths:
    - .m2/repository

maven-build:
  image: maven:3.3.9-jdk-8
  stage: build
  script:
  - "mvn $MAVEN_CLI_OPTS package"
  artifacts:
    paths:
    - target/*.jar
    expire_in: 1 day


playpen-test:
  stage: test
  when: manual
  variables:
    PP_TYPE: DEV
  script:
  - "/home/start.sh"

playpen-deploy:
  stage: deploy
  when: manual
  variables:
    PP_TYPE: PROD
  script:
  - "/home/start.sh"
  only:
  - master